spring.datasource.url=jdbc:postgresql://localhost:5432/Yusra%20DB
spring.datasource.username=postgres
spring.datasource.password=Yusra@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
